// Builds kb.sql: Josh's video transcripts split into overlapping passages, loaded into a D1 FTS5 table
// that Ask Josh searches on every message. Run: node scripts/build-kb.mjs && npx wrangler d1 execute warplan --remote --file kb.sql
import { readFileSync, writeFileSync } from "node:fs";

const SRC = new URL("../../knowledge/josh-transcripts.txt", import.meta.url);
const OUT = new URL("../kb.sql", import.meta.url);
// One transcript per non-empty line, in file order.
const TITLES = [
  "How I bought a clinic with no money down in my early 20s",
  "Live session: buying companies with little to no money down",
  "Cold calls, emails and DMs: what I learned contacting everyone",
  "The numbers: EBITDA, free cash flow and valuing a business",
  "How most deals in the world are actually structured",
  "How I made $150,000 in 12 months from a clinic I didn't pay for",
  "Owners Club Lite course walkthrough",
  "A real deal structure, and using Claude for the numbers",
  "Driving Q&A: business, money and buying companies",
];
const TARGET = 1100, OVERLAP = 200;

const clean = (t) => t
  .replace(/\[ __ \]/g, "[expletive]")
  .replace(/\bJosh Lee\b/g, "Josh Li")
  .replace(/\s+/g, " ")
  .trim();

const videos = readFileSync(SRC, "utf8").replace(/^﻿/, "").split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
if (videos.length !== TITLES.length) throw new Error(`Expected ${TITLES.length} transcripts, found ${videos.length}: update TITLES`);

const chunks = [];
videos.forEach((raw, v) => {
  const sentences = clean(raw).match(/[^.!?]+[.!?]+["')\]]*\s*|[^.!?]+$/g) || [];
  let cur = "";
  for (const s of sentences) {
    if (cur.length + s.length > TARGET && cur.length > 300) {
      chunks.push({ video: TITLES[v], text: cur.trim() });
      cur = cur.slice(-OVERLAP).replace(/^\S*\s/, ""); // carry a little context into the next passage
    }
    cur += s;
  }
  if (cur.trim().length > 80) chunks.push({ video: TITLES[v], text: cur.trim() });
});

const q = (s) => `'${s.replace(/'/g, "''")}'`;
const lines = [
  "-- Generated by scripts/build-kb.mjs from knowledge/josh-transcripts.txt. Safe to re-run.",
  "DROP TABLE IF EXISTS kb;",
  "CREATE VIRTUAL TABLE kb USING fts5(text, video UNINDEXED, tokenize = 'porter unicode61');",
];
for (let i = 0; i < chunks.length; i += 20) {
  lines.push(`INSERT INTO kb (text, video) VALUES\n${chunks.slice(i, i + 20).map((c) => `(${q(c.text)}, ${q(c.video)})`).join(",\n")};`);
}
writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`${videos.length} transcripts → ${chunks.length} passages → kb.sql`);
